### ISSUE TITLE
Release please?

### ISSUE THREAD

**Issue by sysadmiral** [codeclimate/codeclimate-pep8#9]
Could we get a release please? There is a marked difference in the image sizes of the last version and building from HEAD:

```
localhost/codeclimate-pep8             latest              e8088be158ab        34 seconds ago      56.8MB
codeclimate/codeclimate-pep8           latest              3300a9628af5        2 years ago         681MB
```

**Comment by dblandin** [comment]
Hey @sysadmiral,

Thanks for the reminder! I just rolled out an update. Should now be available on our hosted service and via the CLI.

Thanks!

**Comment by dblandin** [comment]
Going to go ahead and close this issue :+1:
